name: my_dorm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  camera: ^0.11.0+2
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  fluentui_system_icons: ^1.1.258
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1
  font_awesome_flutter: ^10.7.0
  googleapis:
  googleapis_auth:
  http:
  image_picker: ^1.1.2
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  permission_handler: ^10.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  table_calendar: ^3.1.2
  timezone: ^0.9.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/service_account.json
    - images/
  fonts:
    - family: Sans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
