name: my_dorm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  fluentui_system_icons: ^1.1.258
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  table_calendar: ^3.1.2
  flutter_local_notifications:
  permission_handler: ^10.0.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Sans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
